#!/bin/bash
#Author: Stephanie

#*********************************************************************************************
#This program install Jenkins on Ubuntu and CentOS
#*********************************************************************************************

echo "This program automatically detects your Operating System and install Jenkins on it"
echo 

echo " checking the linux distribution"
echo

cd /etc/
sudo chmod a+rwx os-release
LINUX=$(cat os-release | grep PRETTY_NAME | awk -F'="' '{print $2}' | cut -c 1-6)


if	[[ $LINUX == Ubuntu ]]; 
then	echo "installing Java and Jenkins on $LINUX"
echo

#*********************************************************************************************
# This section will download and install Jenkins on Ubuntu************************************
#*********************************************************************************************

sudo apt-get update  -y
sudo apt-get search openjdk
sudo apt-get install openjdk-11-jdk -y
sudo apt-get install wget
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins 
sudo systemctl daemon-reload 
sudo systemctl start jenkins
sudo systemctl status jenkins

elif	[[ $LINUX == CentOS ]];
then	echo "installing Java and Jenkins on CentOS"
echo
#*********************************************************************************************
# This section will download and install Jenkins on CentOS************************************
#*********************************************************************************************
sudo yum install wget
sudo yum update –y
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade
sudo yum install jenkins java-1.8.0-openjdk-devel -y 
sudo systemctl daemon-reload 
sudo systemctl start jenkins
sudo systemctl status jenkins

else echo "Program cannot detect your Linux distribution.. bye"
fi
